name: Xodium CI/CD - Quality of Life

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    environment:
      name: "${{ github.ref_name }}"
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v6.0.2

      - id: setup_rust
        name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@d197c158264056996cfba74a9c2d93886346edc3
        with:
          toolchain: stable
          components: rustfmt, clippy

      - id: run_lint
        name: Run Lint
        run: |
          cargo clippy --all-targets --all-features -- -D warnings
          cargo fmt --all -- --check
        shell: bash
